version: "3.8"
services:
  mysql:
    build: ./mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: openDisk
    volumes:
      - mysql-data:/var/lib/mysql
  minio:
    build: ./minio
    container_name: minio_container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456789@A
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: es_single
    environment:
      - node.name=es-node
      - discovery.type=single-node
      - xpack.security.enabled=false       # 开发时禁用安全认证
      - ES_JAVA_OPTS=-Xms512m -Xmx512m     # JVM 内存限制
    ports:
      - "9200:9200"                        # HTTP
      - "9300:9300"                        # 集群通信
    volumes:
      - es-data:/usr/share/elasticsearch/data
  vault:
    command:
      - "server"
    build: ./KES-Vault/docker
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK   # 防止 Vault 使用交换内存，提高安全性
    volumes:
#      - /docker/config/config.hcl:/KES-Vault/docker/config/config.hcl  # 挂载配置文件
      - ./vault_data:/vault/data
    environment:
      VAULT_ADDR: http://127.0.0.1:8200

volumes:
  mysql-data:
  minio-data:
  vault_data:
  es-data:

#networks:
#  ceph-net:
#    external: true