kesvault:
  url: http://192.168.31.4:8004
  secret-path-prefix: user-keys

server:
  port: 8005
spring:
  codec:
    max-in-memory-size: 500MB
  datasource:
    url: jdbc:mysql://192.168.31.4:3306/openDisk
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  webflux:
    multipart:
      max-part-size: 10000MB    # 单个文件最大限制为 10MB
      max-request-size: 100000MB # 整个请求最大限制为 100MB
  servlet:
    multipart:
      max-request-size: 10000MB
      max-file-size: 100000MB
  main:
    web-application-type: reactive

# download-svc/src/main/resources/application.yml

# 这里是必须定义的 minio 配置，给 S3ClientsConfig 注入
minio:
  url: http://192.168.31.4:9000           # 你热存储 MinIO 的地址
  access-key: root               # 你的 MinIO AK
  secret-key: 123456789@A              # 你的 MinIO SK

## （可选）如果 DownloadService 也要访问 Ceph RGW，也一并配置
#ceph:
#  rgw:
#    endpoint: http://192.168.31.32:8000
#    access-key: V5NJ666GBTCXOP7E30CO
#    secret-key: RMJgwAIPBUIiPegvHkN744G5ilmloZn3fwYSgbJA

ceph:
  rgw:
    endpoint: http://192.168.31.4:8000
    access-key: SQ7J77WV118QQK187Y8N
    secret-key: THy4mC4JOGtJc3c8Q4i8snkovQw3VR1H4Jgty0W6

file:
  upload-dir: data
